languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableEmoji = true

theme = "almeida-cv"
disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]

baseURL = "https://example.com/"
title = 'Sumit Mangela | Resume'
#googleAnalytics = ""

[params]
enableMetaTags = false

colorLight = "#fff"
colorText = "#666"
colorPageBackground = "#ddd"
colorPageBackgroundSecondary = "#eaeaea"
colorPrimary = "#ebada9"
colorTextPrimary = "#d47a75"
colorIconPrimary = "#e1a1a0"
colorSecondary = "#aaa"

colorLightDark = "#3d3c3f"
colorTextDark = "#666"
colorPageBackgroundDark = "#ddd"
colorPageBackgroundSecondaryDark = "#eaeaea"
colorPrimaryDark = "#ebada9"
colorTextPrimaryDark = "#d47a75"
colorIconPrimaryDark = "#e1a1a0"
colorSecondaryDark = "#aaa"

pages = 2